prologue: str(required=False, multiline=True)
operations: list(str, required=False)
main-set-up: str(required=False, multiline=True)
main-tear-down: str(required=False, multiline=True)
ansatz-call: include("ansatz-call-def")
---
ansatz-call-def:
  name: str()
  arguments: list(include("ansatz-param"), required=False)
---
ansatz-param:
  name: str()
  symbolic: bool()
  type: str(required=False)
